/**
 * Fuente única de clientes para la galería de la home.
 *
 * `mono` apunta a las variantes monocromas del pipeline, hoy inservibles:
 * `monoInk()` en scripts/process-images.ts pierde el canal alpha al codificar
 * el WebP, así que los 20 archivos `-mono.webp` son bloques sólidos de tinta.
 * No se usan; se conserva el campo para cuando se corrija la generación.
 */
export interface ClientItem {
  id: string;
  name: string;
  category: string;
  sector: "transporte" | "infraestructura" | "corporativo" | "fintech";
  sectorLabel: string;
  impact: string;
  status: string;
  mono: string;
  color: string;
  inverted?: boolean;
  /** Cómo se comporta el master sobre fondo oscuro. Medido, no estimado. */
  tone?: "ink" | "deep";
  metric?: string;
  description: string;
}

export const clientsData: ClientItem[] = [
  {
    id: "unam",
    tone: "ink",
    name: "UNAM",
    category: "Facultad de Odontología",
    sector: "corporativo",
    sectorLabel: "Educación e Institucional",
    impact: "−70% en tiempos de atención presencial",
    status: "Operación activa",
    metric: "−70%",
    mono: "/media/generated/client-logos-unam-escudofacultadodontologiaunam-320-mono.webp",
    color: "/media/generated/client-logos-unam-escudofacultadodontologiaunam-320.webp",
    description: "Digitalización de trámites y expedientes de estudiantes y pacientes, eliminando filas y tiempos muertos.",
  },
  {
    id: "twba",
    name: "TWBA",
    category: "Agencia de Talento",
    sector: "corporativo",
    sectorLabel: "Recursos Humanos",
    impact: "Captura REPSE reducida de 3 días a 20 min",
    status: "Operación activa",
    metric: "20 min",
    mono: "/media/generated/client-logos-twba-logo-blanco-twba-320-mono.webp",
    color: "/media/generated/client-logos-twba-logo-blanco-twba-320.webp",
    inverted: true,
    description: "Automatización de reportes regulatorios REPSE con trazabilidad completa de contratos y nóminas.",
  },
  {
    id: "sgt",
    name: "SGT",
    category: "Seguridad y Gestión",
    sector: "transporte",
    sectorLabel: "Logística y Transporte",
    impact: "100% de reportes con geocerca y foto",
    status: "Operación activa",
    metric: "100%",
    mono: "/media/generated/client-logos-sgt-logo-letras-negras-320-mono.webp",
    color: "/media/generated/client-logos-sgt-logo-letras-negras-320.webp",
    description: "Control en tiempo real de personal y activos en campo con validación fotográfica y GPS.",
  },
  {
    id: "residia",
    tone: "deep",
    name: "Residia",
    category: "Administración Condominal",
    sector: "fintech",
    sectorLabel: "Proptech y Fintech",
    impact: "−60% tiempo en cobranza y reportes",
    status: "Producto en producción",
    metric: "−60%",
    mono: "/media/generated/client-logos-residia-residia-logo-degradado-320-mono.webp",
    color: "/media/generated/client-logos-residia-residia-logo-degradado-320.webp",
    description: "Plataforma integral de control de accesos, estados de cuenta automatizados e incidencias residenciales.",
  },
  {
    id: "icee",
    name: "ICEE",
    category: "Logística Fría",
    sector: "transporte",
    sectorLabel: "Logística y Transporte",
    impact: "−35% incidencias en rutas",
    status: "Operación activa",
    metric: "−35%",
    mono: "/media/generated/client-logos-icee-logo-icee-320-mono.webp",
    color: "/media/generated/client-logos-icee-logo-icee-320.webp",
    description: "Trazabilidad de cadena de distribución, órdenes de servicio y supervisión de puntos de venta.",
  },
  {
    id: "almar",
    tone: "deep",
    name: "Almar Group",
    category: "Operaciones Industriales",
    sector: "fintech",
    sectorLabel: "Industrial y Corporativo",
    impact: "Continuidad operativa 24/7",
    status: "Operación activa",
    mono: "/media/generated/client-logos-almar-almargroup-logo-2025-320-mono.webp",
    color: "/media/generated/client-logos-almar-almargroup-logo-2025-320.webp",
    description: "Sistemas de gestión interna y monitoreo de inventarios para cadena de suministros industrial.",
  },
  {
    id: "auoeste",
    tone: "deep",
    name: "Auoeste",
    category: "Infraestructura Carretera",
    sector: "infraestructura",
    sectorLabel: "Infraestructura",
    impact: "Monitoreo continuo de peajes",
    status: "Operación activa",
    mono: "/media/generated/client-logos-auoeste-logo-auoeste-gris-y-azul-320-mono.webp",
    color: "/media/generated/client-logos-auoeste-logo-auoeste-gris-y-azul-320.webp",
    description: "Modernización de sistemas de reporte operativo y control de flujos vehiculares concesionados.",
  },
  {
    id: "ausol",
    tone: "deep",
    name: "Ausol",
    category: "Concesiones Viales",
    sector: "infraestructura",
    sectorLabel: "Infraestructura",
    impact: "Integración de recaudación y auditoría",
    status: "Operación activa",
    mono: "/media/generated/client-logos-ausol-ausol-logo-baja-320-mono.webp",
    color: "/media/generated/client-logos-ausol-ausol-logo-baja-320.webp",
    description: "Infraestructura de datos para conciliación de aforos y reportes operativos diarios.",
  },
  {
    id: "conedyc",
    tone: "deep",
    name: "Conedyc",
    category: "Construcción e Ingeniería",
    sector: "infraestructura",
    sectorLabel: "Construcción",
    impact: "Control integral de estimaciones",
    status: "Operación activa",
    mono: "/media/generated/client-logos-conedyc-logo-conedyc-oficial-320-mono.webp",
    color: "/media/generated/client-logos-conedyc-logo-conedyc-oficial-320.webp",
    description: "Gestión de proyectos de obra civil, asignación de maquinaria y seguimiento de presupuestos.",
  },
  {
    id: "daysa",
    name: "Daysa",
    category: "Redes Hidráulicas",
    sector: "infraestructura",
    sectorLabel: "Infraestructura",
    impact: "Reportes técnicos en tiempo real",
    status: "Operación activa",
    mono: "/media/generated/client-logos-daysa-copia-de-aysa-1-1-320-mono.webp",
    color: "/media/generated/client-logos-daysa-copia-de-aysa-1-1-320.webp",
    description: "Supervisión de cuadrillas y bitácoras de mantenimiento de redes de distribución.",
  },
  {
    id: "jesalo",
    tone: "deep",
    name: "Jesalo",
    category: "Grupo Inversionista",
    sector: "corporativo",
    sectorLabel: "Corporativo",
    impact: "Consolidación de activos",
    status: "Operación activa",
    mono: "/media/generated/client-logos-jesalo-logo-dark-blue-320-mono.webp",
    color: "/media/generated/client-logos-jesalo-logo-dark-blue-320.webp",
    description: "Plataformas seguras para seguimiento de portafolio y gobernanza de información clave.",
  },
  {
    id: "keedu",
    tone: "deep",
    name: "Keedu",
    category: "Tecnología Educativa",
    sector: "corporativo",
    sectorLabel: "EdTech",
    impact: "Escalabilidad a miles de alumnos",
    status: "Operación activa",
    mono: "/media/generated/client-logos-keedu-keedu-logo-320-mono.webp",
    color: "/media/generated/client-logos-keedu-keedu-logo-320.webp",
    description: "Experiencias de aprendizaje digital interactivas con reportes de avance y retención escolar.",
  },
  {
    id: "lega",
    tone: "deep",
    name: "Lega",
    category: "Servicios Corporativos",
    sector: "corporativo",
    sectorLabel: "Legal & Compliance",
    impact: "Seguridad y cumplimiento documental",
    status: "Operación activa",
    mono: "/media/generated/client-logos-lega-logo-320-mono.webp",
    color: "/media/generated/client-logos-lega-logo-320.webp",
    description: "Control de poderes notariales, expedientes corporativos y trazabilidad de firmas electrónicas.",
  },
  {
    id: "mudarte",
    name: "Mudar-te",
    category: "Logística y Mudanzas",
    sector: "transporte",
    sectorLabel: "Logística y Transporte",
    impact: "Cotización y asignación automática",
    status: "Operación activa",
    mono: "/media/generated/client-logos-mudar-te-versio-n-verde-2-mudar-te-320-mono.webp",
    color: "/media/generated/client-logos-mudar-te-versio-n-verde-2-mudar-te-320.webp",
    description: "Ecosistema digital para cotizaciones en minutos, seguimiento de rutas y liquidaciones a transportistas.",
  },
  {
    id: "okai",
    tone: "ink",
    name: "O-Kai",
    category: "Comercio Mayorista",
    sector: "fintech",
    sectorLabel: "Retail y Distribución",
    impact: "Sincronización omnicanal",
    status: "Operación activa",
    mono: "/media/generated/client-logos-o-kai-logo-320-mono.webp",
    color: "/media/generated/client-logos-o-kai-logo-320.webp",
    description: "Conexión de catálogo, pedidos en ruta e integración directa con sistemas de facturación.",
  },
  {
    id: "ovigas",
    tone: "deep",
    name: "Ovi Gas",
    category: "Distribución de Gas L.P.",
    sector: "infraestructura",
    sectorLabel: "Energía y Distribución",
    impact: "Monitoreo de tanques y rutas",
    status: "Operación activa",
    mono: "/media/generated/client-logos-ovi-gas-logo-ovi-gas-corel-1-320-mono.webp",
    color: "/media/generated/client-logos-ovi-gas-logo-ovi-gas-corel-1-320.webp",
    description: "Rastreo de inventarios en tanques estacionarios y optimización de rutas de reparto a granel.",
  },
  {
    id: "pensiapp",
    name: "Pensiapp",
    category: "Fintech Previsional",
    sector: "fintech",
    sectorLabel: "Fintech",
    impact: "Cálculos de pensión exactos",
    status: "Operación activa",
    mono: "/media/generated/client-logos-pensiapp-pensiapp-logo-320-mono.webp",
    color: "/media/generated/client-logos-pensiapp-pensiapp-logo-320.webp",
    description: "Simuladores actuariales y gestión de trámites de retiro bajo normativas oficiales del IMSS.",
  },
  {
    id: "certa",
    name: "Certa",
    category: "Consultoría y Soluciones",
    sector: "corporativo",
    sectorLabel: "Consultoría",
    impact: "Optimización de flujos de trabajo",
    status: "Operación activa",
    mono: "/media/generated/client-logos-certa-logo-certa-320-mono.webp",
    color: "/media/generated/client-logos-certa-logo-certa-320.webp",
    inverted: true,
    description: "Plataformas a medida para gestión interna y entrega de diagnósticos corporativos.",
  },
  {
    id: "ppservicios",
    tone: "deep",
    name: "PP Servicios",
    category: "Mantenimiento Corporativo",
    sector: "corporativo",
    sectorLabel: "Servicios B2B",
    impact: "Atención de tickets en tiempo récord",
    status: "Operación activa",
    mono: "/media/generated/client-logos-pp-servicios-logo-principal-320-mono.webp",
    color: "/media/generated/client-logos-pp-servicios-logo-principal-320.webp",
    description: "Asignación inteligente de personal técnico y control de órdenes de mantenimiento preventivo.",
  },
  {
    id: "unitrade",
    tone: "deep",
    name: "Unitrade",
    category: "Comercio Exterior y Aduanas",
    sector: "transporte",
    sectorLabel: "Logística y Aduanas",
    impact: "Validación digital de pedimentos",
    status: "Operación activa",
    mono: "/media/generated/client-logos-unitrade-unitrade-logo-320-mono.webp",
    color: "/media/generated/client-logos-unitrade-unitrade-logo-320.webp",
    description: "Visibilidad integral de embarques transfronterizos, integración aduanal y gestión de alertas.",
  },
];
